### ISSUE TITLE
possible improvement

### ISSUE THREAD

**Issue by ctarbide** [howerj/utf8#1]
Hi, just stopping by to let you know that there is a faster implementation down the page http://bjoern.hoehrmann.de/utf-8/decoder/dfa/, from what I understand this other version uses a more aggressive pre computation.

**Comment by howerj** [comment]
Cheers, I'll look into it.

**Comment by howerj** [comment]
Okay, that's done, version "1.0.0" fixes that, it also changes the API and adds actual unit tests. I'd forgotten about this library to be honest, and had left it only half implemented.
